# Generated by Django 6.0 on 2026-01-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_exercise_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='programs',
            name='description',
            field=models.TextField(),
        ),
    ]
