# Generated by Django 6.0 on 2026-01-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_exercise_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
