# Generated by Django 6.0 on 2026-02-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_exercise_image_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
    ]
