# Generated by Django 6.0 on 2026-02-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_socialicons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialicons',
            name='description',
        ),
    ]
